# Generated by Django 3.0.5 on 2020-04-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
